### ISSUE TITLE
code about BeltramiGuard

### ISSUE THREAD

**Issue by yzfxmu** [zknus/Robustness-of-Graph-Neural-Diffusion#1]
Hi,
Thanks for your exciting work.
I would like to know if you can share the code of BeltramiGuard.
It will help significantly to me. Thank you.

**Comment by zknus** [comment]
Hi, BeltramiGurad code updated. 

https://github.com/zknus/Robustness-of-Graph-Neural-Diffusion/blob/f42c166aaa69327782a9e8522b69e77000c25c18/grb/model/torch/belguard.py

**Comment by yzfxmu** [comment]
> Hi, BeltramiGurad code updated.
> 
> https://github.com/zknus/Robustness-of-Graph-Neural-Diffusion/blob/f42c166aaa69327782a9e8522b69e77000c25c18/grb/model/torch/belguard.py

Thanks for your sharing.
